<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByDateAndAuthor($author,$from,$to)
	{
		$qb = $this->createQueryBuilder('a');

		$qb->where('a.author = :author')
			->setParameter('author', $author)
			->andWhere('a.date <= :to')
			->setParameter('to', $to)
			->andWhere('a.date >= :from')
			->setParameter('from', $from)
		;

		return $qb
			->getQuery()
			->getResult()
			;
	}
}
